### ISSUE TITLE
Error with webpack-cli when building

### ISSUE THREAD

**Issue by kanderson91** [noxone/regex-generator#246]
**Describe the bug**
I'm trying to build the project but I get the following error when I run `gradle run`

```
[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
shared             |     at Command.<anonymous> (/app/node_modules/@webpack-cli/serve/lib/index.js:146:35)
shared             |     at async Promise.all (index 1)
shared             |     at async Command.<anonymous> (/app/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```
Seems like this is an issue caused by a recent update from webpack. The solution described here is to upgrade webpack-cli to 4.10.0
https://github.com/webpack/webpack/issues/15951

So I included this line in build.gradle under dependencies:
`implementation npm("webpack-cli", "4.10.0")`

However, then I get this error:
```
Execution failed for task ':packageJson'.
> There is already declared version of 'webpack-cli' with version '4.10.0' which does not intersects with another declared version '4.9.2'
```

I've tried see if there's another dependency that uses webpack-cli 4.9.2 but I can't figure it out. Any help here is much appreciated. This is a great tool and I'd love to try developing with it!

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.2

**Comment by noxone** [comment]
Hi @kanderson91 ,
actually I cannot reproduce this behavior. On my machine everything works fine and also the build process here in the Github Actions works fine (which is most important). I'm working on an M1 Mac with macOS Monterey 12.4, but I doubt, that the OS version will make a huge difference here.

Most of the stuff in the Gradle files is actually generated and Kotlin is taking care of that.
So I cannot really help here, but if somebody else can help, that would be very welcome.

**Comment by leqnam** [comment]
Run the following command:
```
npm uninstall webpack-cli
npm i webpack-cli@4.10.0
``

**Comment by kanderson91** [comment]
Sorry, I meant to say I get this error when I do `gradle run`

```
> [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
  [webpack-cli] TypeError: cli.isMultipleCompiler is not a function
      at Command.<anonymous> (/Users/kenedy/regex-generator/build/js/node_modules/@webpack-cli/serve/lib/index.js:146:35)
      at async Promise.all (index 1)
      at async Command.<anonymous> (/Users/kenedy/regex-generator/build/js/node_modules/webpack-cli/lib/webpack-cli.js:1674:7)
```

So the build works fine, but I'm not able to run it with gradle. @leqnam I tried those commands and I get the same error when I try to run it. If you can't reproduce it though it's probably something with my environment. I can still access the application at least by opening index.html in the build folder.

**Comment by noxone** [comment]
Oh, indeed I have the same behavior on my machine, too. I did not try this for quite a long time.
So the continuous run does not work any more...

**Comment by noxone** [comment]
Oh, but I just accepted the PR #248 to update the Kotlin version to `1.7.10`. Now it works again for me.
@kanderson91 , could you please check again?

**Comment by kanderson91** [comment]
@noxone I just tried that and it works! Thanks for getting back to me.
